---
  - name: Updating remote system
    apt:
      update_cache: yes
  
  - name: Adding gpg key
    shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

  - name: Adding repository 
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present

  - name: Installing grafana
    apt: 
      name: grafana
      state: present
      update_cache: yes

  - name: Enabling and starting grafana service
    service:
      name: grafana-server
      enabled: yes
      state: started
