---
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Creating group
    group:
      name: alertmanager
      system: true
      state: present

  - name: Creating service user
    user:
      name: alertmanager
      create_home: no
      shell: "/usr/sbin/nologin"
      group: prometheus

  - name: Creating directories 
    file:
      path: "{{ item }}"
      state: directory
      owner: alertmanager
      group: alertmanager
    loop:
      - '/tmp/alertmanager'
      - '/etc/alertmanager'
      - '/var/lib/prometheus/alertmanager'

  - name: Downloading source files
    unarchive:
      src: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
      dest: /tmp/alertmanager
      creates: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64
      remote_src: yes

  - name: Coping source files
    copy: 
      src: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64/{{ item }}
      dest: /usr/local/bin/
      remote_src: yes
      mode: preserve
      owner: alertmanager
      group: alertmanager
    loop: 
      - 'alertmanager'
      - 'amtool' 

  - name: Coping config file
    copy: 
      src: /tmp/alertmanager/alertmanager-0.24.0.linux-amd64/alertmanager.yml
      dest: /etc/alertmanager/
      remote_src: yes
      mode: preserve
      owner: alertmanager
      group: alertmanager

  - name: Creating systemd service
    template:
      src: templates/alertmanager.service
      dest: /etc/systemd/system/

  - name: Reloading systemd
    systemd:
      daemon_reload: yes

  - name: Starting service
    systemd:
      name: alertmanager
      state: started
      enabled: yes
